### ISSUE TITLE
Installing finiteflow

### ISSUE THREAD

**Issue by ChristophDl** [peraro/finiteflow#1]
Hi Tiziano,

unfortunately I cannot install finiteflow on my desktop or my notebook. Both have ubuntu, but on the desktop I do not have sudo permissions.

On the notebook, I use

cmake -DMATHLIBINSTALL=/home/christoph/Packages/finiteflowmathlink .
make install

and at the very end I get the error

[100%] Linking CXX shared module fflowmlink.so
/usr/bin/ld: cannot find -luuid
collect2: error: ld returned 1 exit status
CMakeFiles/fflowmlink.dir/build.make:98: recipe for target 'fflowmlink.so' failed

and the folder 'finiteflowmathlink' is empty.

On my desktop I don't have sudo permissions and therefore I installed flint in a custom folder.
I use

cmake -DCMAKE_INSTALL_PREFIX=/home/pcl327b/dlapa/Packages/finiteflowbuild/installfolder -DCMAKE_PREFIX_PATH=/home/pcl327b/dlapa/Packages/finiteflowbuild/dependenciesfolder -DMATHLIBINSTALL=/home/pcl327b/dlapa/Packages/finiteflowbuild/mathinterfacefolder

but I get the error

Could NOT find FLINT (missing: FLINT_LIBRARIES FLINT_INCLUDE_DIRS)

Therefore I tried adding

export LD_LIBRARY_PATH="/home/pcl327b/dlapa/Packages/flint/lib:$LD_LIBRARY_PATH"
export PATH="/home/pcl327b/dlapa/Packages/flint/include/flint:$PATH"

and/or

export FLINT_LIBRARIES="/home/pcl327b/dlapa/Packages/flint/lib"
export FLINT_INCLUDE_DIRS="/home/pcl327b/dlapa/Packages/flint/include/flint"

to my .bash_profile with no change. I also tried

cmake -DCMAKE_INSTALL_PREFIX=/home/pcl327b/dlapa/Packages/finiteflowbuild/installfolder -DCMAKE_PREFIX_PATH=/home/pcl327b/dlapa/Packages/finiteflowbuild/dependenciesfolder -DMATHLIBINSTALL=/home/pcl327b/dlapa/Packages/finiteflowbuild/mathinterfacefolder -FLINT_LIBRARIES=/home/pcl327b/dlapa/Packages/flint/lib -FLINT_INCLUDE_DIRS=/home/pcl327b/dlapa/Packages/flint/include/flint .

with the same result.

Any help is appreciated!

Best,

Christoph

**Comment by peraro** [comment]
The solution to this issue has been added to the FAQ in https://github.com/peraro/finiteflow/commit/04f670100f89be64fe539cd4abc085425a614139.
