### ISSUE TITLE
 error: ‘mp_limb_t’ was not declared in this scope

### ISSUE THREAD

**Issue by jhliu3385** [peraro/finiteflow#5]
Hi Tiziano,

When "sudo make install",  the following erro appeared.

[  2%] Building CXX object CMakeFiles/fflow.dir/src/debug.cc.o
[  5%] Building CXX object CMakeFiles/fflow.dir/src/function_cache.cc.o
In file included from /home/jiahao-virtual/finiteflow/include/fflow/function_cache.hh:6,
                 from /home/jiahao-virtual/finiteflow/src/function_cache.cc:1:
/home/jiahao-virtual/finiteflow/include/fflow/common.hh:34:24: error: ‘mp_limb_t’ was not declared in this scope
   34 |   static_assert(sizeof(mp_limb_t) == sizeof(UInt),
      |                        ^~~~~~~~~
make[2]: *** [CMakeFiles/fflow.dir/build.make:90: CMakeFiles/fflow.dir/src/function_cache.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/fflow.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

I struggled sometime and somehow  "fixed" it by adding "#include <gmp.h>" in "common.hh". Then the installation passed. I don't exactly know how this worked. Is this the right way to fix the error?

Many thanks.

Jiahao

**Comment by peraro** [comment]
Hi, thank you for reporting this. Some recent change in newer versions of FLINT probably require including the GMP header directly in common.h, as you have figured out.  I pushed the fix in 56952f4754712b21d69bed4fdb0ba1fa2617eb2d
